package com.stockflow.inventory.internal.controller;

import com.stockflow.inventory.api.ReserveStockResult;
import com.stockflow.inventory.api.StockAvailability;
import com.stockflow.inventory.api.StockReservation;
import com.stockflow.inventory.internal.controller.dto.ReservationResponse;
import com.stockflow.inventory.internal.controller.dto.StockItemResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.List;

/**
 * DTO mapping, generated by MapStruct at compile time.
 *
 * <p>Used here and not in the persistence layer because these shapes really are field-for-field.
 * {@code unmappedTargetPolicy = ERROR} is the reason to bother: adding a field to a response
 * record and forgetting to populate it becomes a compile error instead of a {@code null} the
 * frontend discovers in production.</p>
 *
 * <p>{@code componentModel = "spring"} makes the generated class a bean, so the controller injects
 * it like anything else rather than calling a static {@code INSTANCE}.</p>
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface InventoryWebMapper {

    @Mapping(target = "id", source = "stockItemId")
    @Mapping(target = "status", constant = "AVAILABLE")
    StockItemResponse toResponse(StockAvailability availability);

    List<StockItemResponse> toResponses(List<StockAvailability> availabilities);

    @Mapping(target = "holds", source = "reservations")
    ReservationResponse toResponse(ReserveStockResult result);

    /**
     * Element mapping for the nested list.
     *
     * <p>MapStruct would generate this implicitly, and it is declared anyway so that a mismatch
     * between {@code StockReservation} and {@code Hold} names the two records in the compile error rather
     * than pointing at the enclosing method.</p>
     */
    ReservationResponse.Hold toHold(StockReservation hold);
}
