package com.stockflow.catalog.internal.controller;

import com.stockflow.catalog.internal.controller.dto.SkuAvailabilityResponse;
import com.stockflow.catalog.internal.domain.SkuAvailability;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.List;

/** DTO mapping, generated by MapStruct; see {@code InventoryWebMapper} for why ERROR on unmapped. */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface CatalogWebMapper {

    @Mapping(target = "sku", source = "sku.code")
    SkuAvailabilityResponse toResponse(SkuAvailability availability);

    List<SkuAvailabilityResponse> toResponses(List<SkuAvailability> availabilities);
}
