package com.stockflow.product.internal.controller;

import com.stockflow.common.audit.AuditEntry;
import com.stockflow.product.api.CreateProductCommand;
import com.stockflow.product.api.ProductSummary;
import com.stockflow.product.api.UpdateProductCommand;
import com.stockflow.product.internal.controller.dto.CreateProductRequest;
import com.stockflow.product.internal.controller.dto.ProductResponse;
import com.stockflow.product.internal.controller.dto.ProductVersionResponse;
import com.stockflow.product.internal.controller.dto.UpdateProductRequest;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.UUID;

/**
 * DTO mapping, generated by MapStruct at compile time. See {@code InventoryWebMapper} for why this
 * is used here and not in the persistence layer, and why {@code unmappedTargetPolicy = ERROR}.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface ProductWebMapper {

    CreateProductCommand toCommand(CreateProductRequest request);

    @Mapping(target = "productId", source = "productId")
    UpdateProductCommand toCommand(UUID productId, UpdateProductRequest request);

    /** {@code status} is {@code ProductStatus} on the summary, {@code String} on the wire — MapStruct
     *  generates the {@code .name()} conversion automatically since the field name matches. */
    ProductResponse toResponse(ProductSummary summary);

    /** {@code action}/{@code outcome} are enums on {@link AuditEntry}, strings on the wire — same
     *  automatic {@code .name()} conversion as {@code toResponse(ProductSummary)} above. */
    ProductVersionResponse toResponse(AuditEntry entry);
}
