package com.stockflow.identity.internal.controller;

import com.stockflow.identity.api.TokenResponse;
import com.stockflow.identity.internal.controller.dto.AuthTokenResponse;

import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/** DTO mapping for the login endpoint, generated by MapStruct at compile time. */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface AuthWebMapper {


    AuthTokenResponse toResponse(TokenResponse token);
}
