package com.stockflow.identity.internal.controller;

import com.stockflow.identity.api.RoleSummary;
import com.stockflow.identity.internal.controller.dto.RoleResponse;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

import java.util.List;

/**
 * DTO mapping, generated by MapStruct at compile time. See
 * {@code inventory.internal.controller.InventoryWebMapper} for the pattern this follows.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface IdentityWebMapper {

    RoleResponse toResponse(RoleSummary summary);

    List<RoleResponse> toResponses(List<RoleSummary> summaries);
}
