package com.stockflow.identity.internal.controller;

import com.stockflow.identity.api.CreatedStaffUser;
import com.stockflow.identity.api.PasswordReset;
import com.stockflow.identity.api.StaffUser;
import com.stockflow.identity.internal.controller.dto.CreatedUserResponse;
import com.stockflow.identity.internal.controller.dto.PasswordResetResponse;
import com.stockflow.identity.internal.controller.dto.UserResponse;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/** DTO mapping for user management, generated by MapStruct (pattern: {@code IdentityWebMapper}). */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface UserManagementWebMapper {

    UserResponse toResponse(StaffUser user);

    CreatedUserResponse toResponse(CreatedStaffUser created);

    PasswordResetResponse toResponse(PasswordReset reset);
}
