package com.stockflow.warehouse.internal.controller;

import com.stockflow.warehouse.api.StorageLocationView;
import com.stockflow.warehouse.internal.controller.dto.BoundaryResponse;
import com.stockflow.warehouse.internal.controller.dto.FootprintResponse;
import com.stockflow.warehouse.internal.controller.dto.ShelfResponse;
import com.stockflow.warehouse.internal.controller.dto.StorageLocationResponse;
import com.stockflow.warehouse.internal.controller.dto.WarehouseLayoutResponse;
import com.stockflow.warehouse.internal.controller.dto.ZoneResponse;
import com.stockflow.warehouse.internal.domain.Footprint;
import com.stockflow.warehouse.internal.domain.PickFaces;
import com.stockflow.warehouse.internal.service.BoundarySummary;
import com.stockflow.warehouse.internal.service.WarehouseLayout;
import com.stockflow.warehouse.internal.service.ZoneSummary;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

/**
 * The map and a looked-up location to responses, generated by MapStruct. Every nested shape is
 * declared, so a field added to one side and not the other is a compile error
 * ({@code unmappedTargetPolicy = ERROR}). The api's enums map to the domain's by constant name.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface LayoutWebMapper {

    WarehouseLayoutResponse toResponse(WarehouseLayout layout);

    WarehouseLayoutResponse.Warehouse toResponse(WarehouseLayout.Warehouse warehouse);

    WarehouseLayoutResponse.Shelf toResponse(WarehouseLayout.Shelf shelf);

    WarehouseLayoutResponse.Level toResponse(WarehouseLayout.Level level);

    WarehouseLayoutResponse.Bin toResponse(WarehouseLayout.Bin bin);

    WarehouseLayoutResponse.Area toResponse(WarehouseLayout.Area area);

    ZoneResponse toResponse(ZoneSummary zone);

    BoundaryResponse toResponse(BoundarySummary boundary);

    FootprintResponse toResponse(Footprint footprint);

    ShelfResponse.PickFaces toResponse(PickFaces pickFaces);

    StorageLocationResponse toResponse(StorageLocationView location);
}
