package com.stockflow.warehouse.internal.controller;

import com.stockflow.warehouse.internal.controller.dto.FootprintRequest;
import com.stockflow.warehouse.internal.controller.dto.FootprintResponse;
import com.stockflow.warehouse.internal.controller.dto.ShelfRequests;
import com.stockflow.warehouse.internal.controller.dto.ShelfResponse;
import com.stockflow.warehouse.internal.domain.BinDefaults;
import com.stockflow.warehouse.internal.domain.BinDetails;
import com.stockflow.warehouse.internal.domain.BinNamingScheme;
import com.stockflow.warehouse.internal.domain.Footprint;
import com.stockflow.warehouse.internal.domain.LevelMeasures;
import com.stockflow.warehouse.internal.domain.LocationSettings;
import com.stockflow.warehouse.internal.domain.PickFaces;
import com.stockflow.warehouse.internal.service.ShelfCommands;
import com.stockflow.warehouse.internal.service.ShelfSummary;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;

import java.util.List;
import java.util.UUID;

/**
 * Shelf requests to commands and summaries to responses.
 *
 * <p>Responses and the small value shapes are generated by MapStruct ({@code unmappedTargetPolicy =
 * ERROR}: a response field nobody fills is a compile error). Commands are written by hand: each
 * assembles domain values ({@link BinDetails}, {@link LocationSettings}, ...) from a flat request,
 * which is clearer as code than as a page of {@code @Mapping}. Building those values validates them,
 * so a bad rotation or a negative elevation becomes a 400 here, before any transaction starts.</p>
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface ShelfWebMapper {

    Footprint toFootprint(FootprintRequest request);

    PickFaces toPickFaces(ShelfRequests.PickFaces request);

    ShelfResponse toResponse(ShelfSummary shelf);

    ShelfResponse.Level toResponse(ShelfSummary.Level level);

    ShelfResponse.Bin toResponse(ShelfSummary.BinEntry bin);

    FootprintResponse toResponse(Footprint footprint);

    /** The filled levels, flattened to one list of bins, each tagged with its level. */
    default List<ShelfResponse.GeneratedBin> toGeneratedBins(List<ShelfSummary.Level> levels) {
        return levels.stream()
                .flatMap(level -> level.bins().stream().map(bin -> new ShelfResponse.GeneratedBin(bin.id(),
                        level.id(), bin.code(), bin.locationId(), bin.locationCode(), toResponse(bin.footprint()))))
                .toList();
    }

    default ShelfCommands.CreateShelf toCommand(UUID warehouseId, ShelfRequests.CreateShelf r) {
        return new ShelfCommands.CreateShelf(warehouseId, r.zoneId(), r.code(), r.name(), r.description(),
                toFootprint(r.footprint()), r.obstacle(), toPickFaces(r.pickFaces()), r.defaultStorageClass());
    }

    default ShelfCommands.UpdateShelf toCommand(UUID shelfId, ShelfRequests.UpdateShelf r) {
        return new ShelfCommands.UpdateShelf(shelfId, r.zoneId(), r.name(), r.description(),
                toFootprint(r.footprint()), r.obstacle(), toPickFaces(r.pickFaces()), r.defaultStorageClass(),
                r.version());
    }

    default ShelfCommands.AddLevel toCommand(UUID shelfId, ShelfRequests.AddLevel r) {
        return new ShelfCommands.AddLevel(shelfId, r.levelIndex(),
                new LevelMeasures(r.elevation(), r.usableHeight(), r.maxWeight()));
    }

    default ShelfCommands.UpdateLevel toCommand(UUID shelfId, UUID levelId, ShelfRequests.UpdateLevel r) {
        return new ShelfCommands.UpdateLevel(shelfId, levelId,
                new LevelMeasures(r.elevation(), r.usableHeight(), r.maxWeight()));
    }

    default ShelfCommands.AddBin toCommand(UUID shelfId, UUID levelId, ShelfRequests.AddBin r) {
        return new ShelfCommands.AddBin(shelfId, levelId, r.code(),
                new BinDetails(r.description(), toFootprint(r.footprint()), r.type(), r.storageClassOverride()),
                new LocationSettings(r.capacityUnits(), r.maxWeight(), r.pickable(), r.putawayTarget()));
    }

    default ShelfCommands.UpdateBin toCommand(UUID shelfId, UUID levelId, UUID binId, ShelfRequests.UpdateBin r) {
        return new ShelfCommands.UpdateBin(shelfId, levelId, binId,
                new BinDetails(r.description(), toFootprint(r.footprint()), r.type(), r.storageClassOverride()),
                new LocationSettings(r.capacityUnits(), r.maxWeight(), r.pickable(), r.putawayTarget()));
    }

    default ShelfCommands.GenerateBins toCommand(UUID shelfId, ShelfRequests.GenerateBins r) {
        ShelfRequests.BinDefaults d = r.defaults();
        return new ShelfCommands.GenerateBins(shelfId, r.levelIds(), r.rowCount(), r.columnCount(),
                r.namingScheme() != null ? r.namingScheme() : BinNamingScheme.SEQUENTIAL,
                new BinDefaults(d.type(), d.storageClassOverride(),
                        new LocationSettings(d.capacityUnits(), d.maxWeight(), d.pickable(), d.putawayTarget())));
    }
}
