package com.stockflow.warehouse.internal.controller;

import com.stockflow.warehouse.internal.controller.dto.CreateZoneRequest;
import com.stockflow.warehouse.internal.controller.dto.RegisterWarehouseRequest;
import com.stockflow.warehouse.internal.controller.dto.UpdateWarehouseRequest;
import com.stockflow.warehouse.internal.controller.dto.UpdateZoneRequest;
import com.stockflow.warehouse.internal.controller.dto.WarehouseResponse;
import com.stockflow.warehouse.internal.controller.dto.ZoneResponse;
import com.stockflow.warehouse.internal.service.CreateZoneCommand;
import com.stockflow.warehouse.internal.service.RegisterWarehouseCommand;
import com.stockflow.warehouse.internal.service.UpdateWarehouseCommand;
import com.stockflow.warehouse.internal.service.UpdateZoneCommand;
import com.stockflow.warehouse.internal.service.WarehouseSummary;
import com.stockflow.warehouse.internal.service.ZoneSummary;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.List;
import java.util.UUID;

/**
 * Request and response mapping, generated by MapStruct. {@code unmappedTargetPolicy = ERROR}: a
 * field added to a response and forgotten here is a compile error, not a {@code null} the frontend
 * finds later.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface WarehouseWebMapper {

    RegisterWarehouseCommand toCommand(RegisterWarehouseRequest request);

    @Mapping(target = "expectedVersion", source = "request.version")
    UpdateWarehouseCommand toCommand(UUID warehouseId, UpdateWarehouseRequest request);

    CreateZoneCommand toCommand(UUID warehouseId, CreateZoneRequest request);

    @Mapping(target = "expectedVersion", source = "request.version")
    UpdateZoneCommand toCommand(UUID zoneId, UpdateZoneRequest request);

    WarehouseResponse toResponse(WarehouseSummary warehouse);

    ZoneResponse toResponse(ZoneSummary zone);

    List<ZoneResponse> toZoneResponses(List<ZoneSummary> zones);
}
