package com.stockflow.procurement.internal.controller;

import com.stockflow.procurement.api.CreatePOLineCommand;
import com.stockflow.procurement.api.CreatePurchaseOrderCommand;
import com.stockflow.procurement.api.POLineSummary;
import com.stockflow.procurement.api.PurchaseOrderSummary;
import com.stockflow.procurement.internal.controller.dto.CreatePOLineRequest;
import com.stockflow.procurement.internal.controller.dto.CreatePurchaseOrderRequest;
import com.stockflow.procurement.internal.controller.dto.POLineResponse;
import com.stockflow.procurement.internal.controller.dto.PurchaseOrderResponse;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

/**
 * DTO mapping, generated by MapStruct at compile time. See {@code InventoryWebMapper} for why this
 * is used here and not in the persistence layer, and why {@code unmappedTargetPolicy = ERROR}.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
interface PurchaseOrderWebMapper {

    CreatePurchaseOrderCommand toCommand(CreatePurchaseOrderRequest request);

    CreatePOLineCommand toCommand(CreatePOLineRequest request);

    PurchaseOrderResponse toResponse(PurchaseOrderSummary summary);

    @Mapping(target = "openQuantity", expression = "java(summary.openQuantity())")
    POLineResponse toResponse(POLineSummary summary);
}
